# Generated by Django 6.1.1 on 2026-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekeningnummer', models.CharField(max_length=20)),
                ('transactiedatum', models.DateField()),
                ('bedrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('omschrijving', models.TextField()),
                ('categorie', models.CharField(default='Overig', max_length=50)),
            ],
        ),
    ]
